Create patch set 22
Change has been successfully rebased and submitted as a2872635476d84369312a4914b171b65f660f731

14 is the latest approved patch-set.
The change was submitted with unreviewed changes in the following files:

```
The name of the file: extension/extension_tool.cue
Insertions: 3, Deletions: 2.

@@ -5,6 +5,7 @@
 	"list"
 	"strings"
 
+	"tool/cli"
 	"tool/exec"
 	"tool/file"
 )
@@ -36,6 +37,9 @@
 // genPackageJSON generates an npm package.json file from the current site configuration.
 command: genPackageJSON: write: file.Create & {
 	filename: "package.json"
+
+	// json.Indent does not produce a trailing newline. Hence we include one
+	// "manually" here.
 	contents: """
 		\(json.Indent(json.Marshal(extension.npm), "", "  "))
 
@@ -73,8 +77,8 @@
 	let commitVersion = "v" + extension.npm.version
 
 	if commitVersion != _version {
-		msg: exec.Run & {
-			cmd: ["echo", "commitVersion \(commitVersion) != tag version \(_version)", "&&", "false"]
+		msg: cli.Print & {
+			text: "commitVersion \(commitVersion) != tag version \(_version)"
 		}
 		error: exec.Run & {
 			$after: msg
```


Patch-set: 22
Patch-set-description: Rebase
Subject: internal/ci: update trybot workflow to also do releases
Status: merged
Commit: a2872635476d84369312a4914b171b65f660f731
Tag: autogenerated:gerrit:merged
Groups: c2a518d1d8660d3bc2c97d7d390ea1f3bbaa6a77
Label: Code-Review=+2, df6713ddf66051f3bed55c83fdc846b02a69a0d6 Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: TryBot-Result=+1, 7c3101b136b1330c19242a8f5f93c615b6f2c29f Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Label: SUBM=+1, 5710d4b33f7517e618e81062119fddffb05da8cf
Submission-id: 1204649
Submitted-with: OK
Submitted-with: Rule-Name: gerrit~DefaultSubmitRule
Submitted-with: MAY: Code-Review: Gerrit User 1017720 <1017720@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: TryBot-Result: Gerrit User 1017882 <1017882@d5d70762-12d0-45a1-890d-524b12d3f735>
Submitted-with: MAY: Hold
Attention: {"person_ident":"Gerrit User 1017723 \u003c1017723@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}
Attention: {"person_ident":"Gerrit User 1017882 \u003c1017882@d5d70762-12d0-45a1-890d-524b12d3f735\u003e","operation":"REMOVE","reason":"Change was submitted"}